# Generated by Django 2.2.6 on 2019-11-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191116_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeranswer',
            old_name='answer',
            new_name='question',
        ),
    ]
