# Generated by Django 2.2.6 on 2019-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_playeranswer_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
