# Generated by Django 2.2.6 on 2019-11-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
