# Generated by Django 3.2.7 on 2021-09-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundLength', models.IntegerField()),
                ('timer', models.IntegerField()),
            ],
        ),
    ]
