# Generated by Django 3.2.7 on 2021-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_gameover'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='roundEndTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
