# Generated by Django 3.2.7 on 2021-09-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_player_informant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='roundOneEndTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roundThreeEndTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='roundTwoEndTime',
            field=models.IntegerField(default=0),
        ),
    ]
