# Generated by Django 3.2.7 on 2021-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20210921_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activeScreen',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
