# Generated by Django 3.2.7 on 2021-09-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_player_activescreen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='activeScreen',
            new_name='active_screen',
        ),
    ]
