# Generated by Django 3.2.4 on 2021-09-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_rename_activescreen_player_active_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
