# Generated by Django 3.2.4 on 2021-09-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_player_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
