# Generated by Django 3.2.4 on 2021-09-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_player_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected_count',
            field=models.IntegerField(default=0),
        ),
    ]
