# Generated by Django 3.2.7 on 2021-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_question_selected_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(default='detective', max_length=100),
        ),
    ]
