# Generated by Django 3.2.7 on 2021-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_been_informant',
            field=models.BooleanField(default=False),
        ),
    ]
