# Generated by Django 3.2.7 on 2021-10-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_player_has_been_informant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='announce_round_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='announce_round_3',
            field=models.BooleanField(default=True),
        ),
    ]
