# Generated by Django 3.2.7 on 2021-10-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20210930_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='high_accuracy_question',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='low_accuracy_question',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='med_accuracy_question',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
