# Generated by Django 3.2.7 on 2021-10-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20211004_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='debug',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='roundLength',
            field=models.IntegerField(default=30),
        ),
    ]
