# Generated by Django 3.2.7 on 2021-10-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20211007_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='debug_roundLength',
            field=models.IntegerField(default=30),
        ),
    ]
