# Generated by Django 3.2.7 on 2021-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_game_debug_roundlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='safe_list',
            field=models.TextField(null=True),
        ),
    ]
