# Generated by Django 3.2.7 on 2021-10-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_player_safe_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='safe_list',
            new_name='safe_list_1',
        ),
    ]
