# Generated by Django 3.2.7 on 2021-10-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_rename_safe_list_player_safe_list_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='safe_list_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='safe_list_3',
            field=models.TextField(null=True),
        ),
    ]
