# Generated by Django 3.2.7 on 2021-10-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20211007_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='private_tip',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='safe_list_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='safe_list_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='safe_list_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
