# Generated by Django 3.2.7 on 2021-10-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeranswer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playermessages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
