# Generated by Django 3.2.7 on 2021-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_auto_20211012_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='roundZeroEndTime',
            field=models.IntegerField(default=0),
        ),
    ]
