# Generated by Django 3.2.7 on 2021-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_game_debug_pregamelength'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pregameLength',
            field=models.IntegerField(default=30),
        ),
    ]
