# Generated by Django 3.2.7 on 2021-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_game_pregamelength'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='announce_round_1',
            field=models.BooleanField(default=True),
        ),
    ]
