# Generated by Django 3.2.7 on 2021-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_alter_player_private_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='override_screen',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
