# Generated by Django 3.2.7 on 2021-10-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_game_death_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='announce_round_4',
            field=models.BooleanField(default=True),
        ),
    ]
