# Generated by Django 3.2.7 on 2021-10-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_rename_logs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='events',
            field=models.TextField(default=''),
        ),
    ]
