# Generated by Django 3.2.7 on 2021-10-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_log_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='GameLog',
        ),
    ]
