# Generated by Django 3.2.7 on 2021-10-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_rename_log_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='event',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='player',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
