# Generated by Django 3.2.7 on 2021-10-20 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0048_auto_20211019_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='events',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
