# Generated by Django 3.2.7 on 2021-10-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_auto_20211019_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='player',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
