# Generated by Django 3.2.7 on 2021-10-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0050_alter_gamelog_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='datetime',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
