# Generated by Django 3.2.7 on 2021-10-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_alter_gamelog_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameOver',
            new_name='gameOverTime',
        ),
    ]
