# Generated by Django 3.2.7 on 2021-10-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_rename_gameover_game_gameovertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=True),
        ),
    ]
