# Generated by Django 3.2.4 on 2021-10-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0054_player_informing_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='private_tip',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
