# Generated by Django 3.2.7 on 2021-10-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0055_auto_20211024_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
