# Generated by Django 3.2.7 on 2021-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_game_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='roundFourEndTime',
            field=models.IntegerField(default=0),
        ),
        # migrations.AlterField(
        #     model_name='game',
        #     name='game_start_time',
        #     field=models.IntegerField(default=0),
        # ),
    ]
