# Generated by Django 3.2.7 on 2021-10-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0057_auto_20211026_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_start_time',
        ),
    ]
