# Generated by Django 3.2.7 on 2021-10-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0060_game_initial_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_second_tip_sent',
            field=models.BooleanField(default=False),
        ),
    ]
