# Generated by Django 3.2.7 on 2021-10-28 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0062_auto_20211027_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='death_alert',
        ),
        migrations.AddField(
            model_name='player',
            name='death_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_requests_created', to='game.player'),
        ),
    ]
